name: "Bug report"
description: "Did you find a bug? Report it with this template."
title: "[Bug] "
labels: ["bug"]
projects: ["pvarki/24"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "# Bug"
  - type: markdown
    attributes:
      value: "## What - Describe the bug"
  - type: textarea
    id: bug-description
    attributes:
      description: "Outline the bug. What is it, and what does it affect?"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## What I expected to happen"
  - type: textarea
    id: expected-behavior
    attributes:
      description: "What were you doing, and what did you expect to happen?"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## What happened instead"
  - type: textarea
    id: actual-behavior
    attributes:
      description: "What happened instead?"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "# Additional information (Optional)"
  - type: markdown
    attributes:
      value: "## Screenshots"
  - type: textarea
    id: screenshots
    attributes:
      description: "If applicable, screenshots are of much help."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## How to reproduce the bug?"
  - type: textarea
    id: steps-to-reproduce
    attributes:
      description: |
        Outline steps, that you think to be necessary to replicate of this bug.
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. Get the error message
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## User configuration"
  - type: textarea
    id: user-configuration
    attributes:
      description: "Under what configuration you ran into the bug? E.g. with which device, browser and under which conditions server was ran, as far as you know."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "# Why & Workaround (Optional)"
  - type: markdown
    attributes:
      value: "## Why the bug happens?"
  - type: textarea
    id: reason
    attributes:
      description: "If you know or guess the reason behind the bug, tell it here."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Workaround"
  - type: textarea
    id: workaround
    attributes:
      description: "If you know a workaround (not a fix, but ability to continue operation even if the bug's in place), tell it here."
    validations:
      required: false
