name: "Feature request"
description: "Got an idea? Want something new? Suggest it with this Feature Request template!"
title: "[Feature Request] "
projects: ["pvarki/24"]
labels: ["enhancement"]
assignees: []
body:
  - type: textarea
    id: request-about
    attributes:
      label: "What's your request about? Describe the solution you'd like"
      description: "Describe, what you want to happen."
    validations:
      required: true
  - type: textarea
    id: product-components
    attributes:
      label: "Which product(s)?"
      description: "If you can, point to product(s) or component(s) that should have this feature."
    validations:
      required: false
  - type: textarea
    id: business-problem
    attributes:
      label: "Describe the Business Problem"
      description: "Which kind of user would need this and why, for what value? If you know our user types, please use them, or even better, write the Why as a user story."
    validations:
      required: true
  - type: textarea
    id: implementation-ideas
    attributes:
      label: "How should this feature be implemented?"
      description: "If you have ideas on how you would like to this feature to work, describe them here - much helpful!"
    validations:
      required: false
  - type: textarea
    id: alternative-ideas
    attributes:
      label: "Describe alternatives you've considered"
      description: "If you have even alternative ideas on how it would work, this is the place to write them down."
    validations:
      required: false
  - type: textarea
    id: technical-implementation
    attributes:
      label: "How this feature could be implemented?"
      description: "If you know, describe here how this feature could be implemented technically."
    validations:
      required: false
